### ISSUE TITLE
how about <stl:search > use demo

### ISSUE THREAD

**Issue by 13hua** [siteserver/template-zotikos#1]
I use <stl:search >  do a search  function , this demo is form submit to new page, but I do not want to next page ,  how can i do?  
i use the next code,but it is not todo.
 <stl:search pageNum="12" isDefaultDisplay="true"></stl:search>

我要做一个搜索功能，这个demo里面是form提交，跳转到新的页面，但是我不想调转页面，请问要怎么做？
文档中的 <stl:search pageNum="12" isDefaultDisplay="true"></stl:search> 这个标签我使用了之后  并没有进行编译

**Comment by starlying** [comment]
可以到模板管理，找到搜索页面的代码，贴到当前模板里面，再把form提交的页面改成本页面

**Comment by 13hua** [comment]
这个<stl:search >标签搜索的是哪部分内容呢？为什么一直都是搜索不到内容呢？要怎么样才能搜索不到内容呢？

**Comment by starlying** [comment]
可以参考一下stl语言，http://stl.siteserver.cn

**Comment by 13hua** [comment]
非常感谢耐心解答，解决了
<stl:searchinput searchurl="{Stl.SiteUrl}/search.html">
            <input type="text" id="word" class="search-input">
            <button id="submit" class="search-submit" style="width: 102px; height: 51px; color: #fff; font-size: 12px; background: #A81504; border: none; border-radius: 4px;">搜索</button>
        </stl:searchinput>
通过id来传递输入的搜索关键字，form的方式stl标签根本就不会编译
